[build]
  command = "npm run build"
  publish = "dist"

# Redirection rule for Single Page Apps (SPA) like React
# Prevents 404 errors when refreshing a page like /mural
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
