
import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';

export function useSupabase<T extends { id: string }>(tableName: string) {
    const [data, setData] = useState<T[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    const fetchData = async () => {
        try {
            const { data: result, error } = await supabase
                .from(tableName)
                .select('*')
                .order('created_at', { ascending: false });

            if (error) throw error;
            setData(result as T[] || []);
        } catch (err: any) {
            console.error(`Error fetching ${tableName}:`, err);
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchData();

        const channel = supabase
            .channel(`public:${tableName}`)
            .on('postgres_changes', { event: '*', schema: 'public', table: tableName }, (payload) => {
                const { eventType, new: newRow, old: oldRow } = payload;

                setData((currentData) => {
                    if (eventType === 'INSERT') {
                        return [newRow as T, ...currentData];
                    } else if (eventType === 'UPDATE') {
                        return currentData.map(item => item.id === (newRow as T).id ? (newRow as T) : item);
                    } else if (eventType === 'DELETE') {
                        return currentData.filter(item => item.id !== (oldRow as T).id);
                    }
                    return currentData;
                });
            })
            .subscribe();

        return () => {
            supabase.removeChannel(channel);
        };
    }, [tableName]);

    const create = async (item: Partial<T>) => {
        // Remove 'id' if it's auto-generated by DB or handle it. 
        // We generally let DB generate UUIDs, but if code generates ID, that's fine too.
        // Let's remove explicit ID if it looks like a timestamp (from prev code) to let DB handle UUIDv4
        // But for compatibility with existing types, let's keep it flexible.

        // Fix: Don't destructure if we aren't using them, to avoid TS build errors.
        // const { id, ..._rest } = item as any; 

        const { error } = await supabase.from(tableName).insert([item]);
        if (error) {
            console.error('Error creating:', error);
            alert('Erro ao salvar: ' + error.message);
        }
    };

    const update = async (id: string, updates: Partial<T>) => {
        const { error } = await supabase.from(tableName).update(updates).eq('id', id);
        if (error) console.error('Error updating:', error);
    };

    const remove = async (id: string) => {
        const { error } = await supabase.from(tableName).delete().eq('id', id);
        if (error) console.error('Error deleting:', error);
    };

    return { data, loading, error, create, update, remove };
}
